/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SwarmRouteImport } from './routes/swarm'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as RagRouteImport } from './routes/rag'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as PersonaRouteImport } from './routes/persona'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as MessagingRouteImport } from './routes/messaging'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CronRouteImport } from './routes/cron'
import { Route as CodeGraphRouteImport } from './routes/code-graph'
import { Route as CliBridgesRouteImport } from './routes/cli-bridges'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BrowserRouteImport } from './routes/browser'
import { Route as BrainRouteImport } from './routes/brain'
import { Route as IndexRouteImport } from './routes/index'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SwarmRoute = SwarmRouteImport.update({
  id: '/swarm',
  path: '/swarm',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const RagRoute = RagRouteImport.update({
  id: '/rag',
  path: '/rag',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonaRoute = PersonaRouteImport.update({
  id: '/persona',
  path: '/persona',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagingRoute = MessagingRouteImport.update({
  id: '/messaging',
  path: '/messaging',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CronRoute = CronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeGraphRoute = CodeGraphRouteImport.update({
  id: '/code-graph',
  path: '/code-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const CliBridgesRoute = CliBridgesRouteImport.update({
  id: '/cli-bridges',
  path: '/cli-bridges',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowserRoute = BrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainRoute = BrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brain': typeof BrainRoute
  '/browser': typeof BrowserRoute
  '/chat': typeof ChatRoute
  '/cli-bridges': typeof CliBridgesRoute
  '/code-graph': typeof CodeGraphRoute
  '/cron': typeof CronRoute
  '/dashboard': typeof DashboardRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/mcp': typeof McpRoute
  '/memory': typeof MemoryRoute
  '/messaging': typeof MessagingRoute
  '/office': typeof OfficeRoute
  '/persona': typeof PersonaRoute
  '/profiles': typeof ProfilesRoute
  '/providers': typeof ProvidersRoute
  '/rag': typeof RagRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/swarm': typeof SwarmRoute
  '/tasks': typeof TasksRoute
  '/terminal': typeof TerminalRoute
  '/usage': typeof UsageRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brain': typeof BrainRoute
  '/browser': typeof BrowserRoute
  '/chat': typeof ChatRoute
  '/cli-bridges': typeof CliBridgesRoute
  '/code-graph': typeof CodeGraphRoute
  '/cron': typeof CronRoute
  '/dashboard': typeof DashboardRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/mcp': typeof McpRoute
  '/memory': typeof MemoryRoute
  '/messaging': typeof MessagingRoute
  '/office': typeof OfficeRoute
  '/persona': typeof PersonaRoute
  '/profiles': typeof ProfilesRoute
  '/providers': typeof ProvidersRoute
  '/rag': typeof RagRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/swarm': typeof SwarmRoute
  '/tasks': typeof TasksRoute
  '/terminal': typeof TerminalRoute
  '/usage': typeof UsageRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brain': typeof BrainRoute
  '/browser': typeof BrowserRoute
  '/chat': typeof ChatRoute
  '/cli-bridges': typeof CliBridgesRoute
  '/code-graph': typeof CodeGraphRoute
  '/cron': typeof CronRoute
  '/dashboard': typeof DashboardRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/mcp': typeof McpRoute
  '/memory': typeof MemoryRoute
  '/messaging': typeof MessagingRoute
  '/office': typeof OfficeRoute
  '/persona': typeof PersonaRoute
  '/profiles': typeof ProfilesRoute
  '/providers': typeof ProvidersRoute
  '/rag': typeof RagRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/swarm': typeof SwarmRoute
  '/tasks': typeof TasksRoute
  '/terminal': typeof TerminalRoute
  '/usage': typeof UsageRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brain'
    | '/browser'
    | '/chat'
    | '/cli-bridges'
    | '/code-graph'
    | '/cron'
    | '/dashboard'
    | '/groups'
    | '/login'
    | '/marketplace'
    | '/mcp'
    | '/memory'
    | '/messaging'
    | '/office'
    | '/persona'
    | '/profiles'
    | '/providers'
    | '/rag'
    | '/sessions'
    | '/settings'
    | '/skills'
    | '/swarm'
    | '/tasks'
    | '/terminal'
    | '/usage'
    | '/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brain'
    | '/browser'
    | '/chat'
    | '/cli-bridges'
    | '/code-graph'
    | '/cron'
    | '/dashboard'
    | '/groups'
    | '/login'
    | '/marketplace'
    | '/mcp'
    | '/memory'
    | '/messaging'
    | '/office'
    | '/persona'
    | '/profiles'
    | '/providers'
    | '/rag'
    | '/sessions'
    | '/settings'
    | '/skills'
    | '/swarm'
    | '/tasks'
    | '/terminal'
    | '/usage'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/brain'
    | '/browser'
    | '/chat'
    | '/cli-bridges'
    | '/code-graph'
    | '/cron'
    | '/dashboard'
    | '/groups'
    | '/login'
    | '/marketplace'
    | '/mcp'
    | '/memory'
    | '/messaging'
    | '/office'
    | '/persona'
    | '/profiles'
    | '/providers'
    | '/rag'
    | '/sessions'
    | '/settings'
    | '/skills'
    | '/swarm'
    | '/tasks'
    | '/terminal'
    | '/usage'
    | '/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrainRoute: typeof BrainRoute
  BrowserRoute: typeof BrowserRoute
  ChatRoute: typeof ChatRoute
  CliBridgesRoute: typeof CliBridgesRoute
  CodeGraphRoute: typeof CodeGraphRoute
  CronRoute: typeof CronRoute
  DashboardRoute: typeof DashboardRoute
  GroupsRoute: typeof GroupsRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  McpRoute: typeof McpRoute
  MemoryRoute: typeof MemoryRoute
  MessagingRoute: typeof MessagingRoute
  OfficeRoute: typeof OfficeRoute
  PersonaRoute: typeof PersonaRoute
  ProfilesRoute: typeof ProfilesRoute
  ProvidersRoute: typeof ProvidersRoute
  RagRoute: typeof RagRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  SwarmRoute: typeof SwarmRoute
  TasksRoute: typeof TasksRoute
  TerminalRoute: typeof TerminalRoute
  UsageRoute: typeof UsageRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swarm': {
      id: '/swarm'
      path: '/swarm'
      fullPath: '/swarm'
      preLoaderRoute: typeof SwarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rag': {
      id: '/rag'
      path: '/rag'
      fullPath: '/rag'
      preLoaderRoute: typeof RagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persona': {
      id: '/persona'
      path: '/persona'
      fullPath: '/persona'
      preLoaderRoute: typeof PersonaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messaging': {
      id: '/messaging'
      path: '/messaging'
      fullPath: '/messaging'
      preLoaderRoute: typeof MessagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron': {
      id: '/cron'
      path: '/cron'
      fullPath: '/cron'
      preLoaderRoute: typeof CronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-graph': {
      id: '/code-graph'
      path: '/code-graph'
      fullPath: '/code-graph'
      preLoaderRoute: typeof CodeGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli-bridges': {
      id: '/cli-bridges'
      path: '/cli-bridges'
      fullPath: '/cli-bridges'
      preLoaderRoute: typeof CliBridgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browser': {
      id: '/browser'
      path: '/browser'
      fullPath: '/browser'
      preLoaderRoute: typeof BrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain': {
      id: '/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof BrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrainRoute: BrainRoute,
  BrowserRoute: BrowserRoute,
  ChatRoute: ChatRoute,
  CliBridgesRoute: CliBridgesRoute,
  CodeGraphRoute: CodeGraphRoute,
  CronRoute: CronRoute,
  DashboardRoute: DashboardRoute,
  GroupsRoute: GroupsRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  McpRoute: McpRoute,
  MemoryRoute: MemoryRoute,
  MessagingRoute: MessagingRoute,
  OfficeRoute: OfficeRoute,
  PersonaRoute: PersonaRoute,
  ProfilesRoute: ProfilesRoute,
  ProvidersRoute: ProvidersRoute,
  RagRoute: RagRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  SwarmRoute: SwarmRoute,
  TasksRoute: TasksRoute,
  TerminalRoute: TerminalRoute,
  UsageRoute: UsageRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
